-- ============================================================
-- Pempek Website — Full Supabase Schema (run once in SQL Editor)
-- ============================================================

-- ─── Storage: bucket "images" (public, max 5MB per file) ───
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('images', 'images', true, 5242880)
ON CONFLICT (id) DO NOTHING;

-- Allow anonymous uploads to bucket 'images'
CREATE POLICY "anon upload images" ON storage.objects
  FOR INSERT TO anon WITH CHECK (bucket_id = 'images');
CREATE POLICY "anon update images" ON storage.objects
  FOR UPDATE TO anon USING (bucket_id = 'images');
CREATE POLICY "anon delete images" ON storage.objects
  FOR DELETE TO anon USING (bucket_id = 'images');

-- ─── Products ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  price NUMERIC NOT NULL DEFAULT 0,
  price_strikethrough NUMERIC,
  category_id BIGINT,
  short_description TEXT DEFAULT '',
  full_description TEXT DEFAULT '',
  composition TEXT DEFAULT '',
  stock INT DEFAULT 0,
  weight INT DEFAULT 100,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','draft')),
  is_best_seller BOOLEAN DEFAULT false,
  is_featured BOOLEAN DEFAULT false,
  ord INT DEFAULT 0,
  thumbnail TEXT DEFAULT '',
  images JSONB DEFAULT '[]',
  seo_title TEXT,
  seo_description TEXT,
  meta_keywords TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ─── Categories ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  icon TEXT,
  ord INT DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','draft'))
);

-- ─── Articles ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  thumbnail TEXT DEFAULT '',
  category TEXT DEFAULT 'Umum',
  content TEXT DEFAULT '',
  author TEXT DEFAULT 'Admin',
  date DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'draft' CHECK (status IN ('published','draft')),
  seo_title TEXT,
  seo_description TEXT,
  meta_keywords TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ─── Banners ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT DEFAULT '',
  subtitle TEXT DEFAULT '',
  button_text TEXT DEFAULT '',
  button_link TEXT DEFAULT '',
  background_image TEXT DEFAULT '',
  status TEXT DEFAULT 'active' CHECK (status IN ('active','draft'))
);

-- ─── FAQs ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT DEFAULT '',
  ord INT DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active','draft'))
);

-- ─── Testimonials ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  photo TEXT DEFAULT '',
  rating INT DEFAULT 5,
  comment TEXT DEFAULT '',
  status TEXT DEFAULT 'active' CHECK (status IN ('active','draft'))
);

-- ─── Gallery ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  images JSONB DEFAULT '[]',
  caption TEXT DEFAULT '',
  category TEXT DEFAULT ''
);

-- ─── Packages ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  items JSONB DEFAULT '[]',
  price NUMERIC NOT NULL DEFAULT 0,
  original_price NUMERIC,
  badge TEXT DEFAULT '',
  is_featured BOOLEAN DEFAULT false
);

-- ─── Page Views (visitor tracking) ─────────────────────────
CREATE TABLE IF NOT EXISTS public.page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path TEXT NOT NULL DEFAULT '/',
  ip TEXT DEFAULT '',
  user_agent TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ─── Orders ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  whatsapp TEXT DEFAULT '',
  products JSONB DEFAULT '[]',
  notes TEXT DEFAULT '',
  date TIMESTAMPTZ DEFAULT now(),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','cancelled'))
);

-- ─── Settings (single row, id=1) ───────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
  id INT PRIMARY KEY DEFAULT 1,
  logo TEXT DEFAULT '',
  site_name TEXT DEFAULT 'Pempek Palembang',
  address TEXT DEFAULT '',
  whatsapp TEXT DEFAULT '',
  instagram TEXT DEFAULT '',
  facebook TEXT DEFAULT '',
  tiktok TEXT DEFAULT '',
  google_maps_embed TEXT DEFAULT '',
  email TEXT DEFAULT '',
  operating_hours TEXT DEFAULT '',
  footer_text TEXT DEFAULT '',
  about_us TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ─── SEO (single row, id=1) ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.seo (
  id INT PRIMARY KEY DEFAULT 1,
  meta_title TEXT DEFAULT '',
  meta_description TEXT DEFAULT '',
  keywords TEXT DEFAULT '',
  og_image TEXT DEFAULT '',
  canonical_url TEXT DEFAULT '',
  robots TEXT DEFAULT 'index, follow',
  google_verification TEXT DEFAULT '',
  schema_json_ld TEXT DEFAULT '',
  favicon TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO public.seo (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ─── RLS: enable + policies ────────────────────────────────
ALTER TABLE public.products    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packages    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_views  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seo         ENABLE ROW LEVEL SECURITY;

-- Public read access (website front-end)
CREATE POLICY "anon read products"    ON public.products    FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "anon read categories"  ON public.categories  FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "anon read articles"    ON public.articles    FOR SELECT TO anon USING (status = 'published');
CREATE POLICY "anon read banners"     ON public.banners     FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "anon read faqs"        ON public.faqs        FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "anon read testimonials" ON public.testimonials FOR SELECT TO anon USING (status = 'active');
CREATE POLICY "anon read gallery"     ON public.gallery     FOR SELECT TO anon USING (true);
CREATE POLICY "anon read packages"    ON public.packages    FOR SELECT TO anon USING (true);
-- page_views: anon boleh INSERT (tracking), TIDAK boleh SELECT (privasi)
CREATE POLICY "anon insert page_views" ON public.page_views FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "anon read settings"    ON public.settings    FOR SELECT TO anon USING (true);
CREATE POLICY "anon read seo"         ON public.seo         FOR SELECT TO anon USING (true);
-- orders: NO anon read (privacy). Admin CRUD uses service key which bypasses RLS.

-- Authenticated (Supabase Auth users) get full CRUD — optional; service key bypasses RLS anyway.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['products','categories','articles','banners','faqs','testimonials','gallery','packages','orders','settings','seo','page_views'] LOOP
    EXECUTE format('CREATE POLICY "auth full access %s" ON public.%I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t, t);
  END LOOP;
END $$;

-- ─── Auto-update updated_at trigger ────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_products_updated  BEFORE UPDATE ON public.products  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_articles_updated  BEFORE UPDATE ON public.articles  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_settings_updated  BEFORE UPDATE ON public.settings  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_seo_updated       BEFORE UPDATE ON public.seo       FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─── Decrement product stock atomically (dipakai saat order dibuat) ──
CREATE OR REPLACE FUNCTION decrement_stock(p_product_id BIGINT, p_qty INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE updated_rows INT;
BEGIN
  UPDATE public.products
     SET stock = GREATEST(stock - p_qty, 0)
   WHERE id = p_product_id AND stock >= p_qty;
  GET DIAGNOSTICS updated_rows = ROW_COUNT;
  RETURN updated_rows > 0;
END;
$$;
